remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: false
github:
  is_project_page: false
  home: /index
  tasks: /tasks/
  data: /data/
  evaluation: /evaluation/
  timeline: /timeline/
  workshop: /workshop/
  organizers: /organizers/


theme: jekyll-theme-cayman